var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/customers/group_party/page.js")
R.c("server/chunks/ssr/_c4bc155d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/_bfda793d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ef35174._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a407645._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_customers_group_party_page_actions_c126a5fc.js")
R.m(50896)
module.exports=R.m(50896).exports
