// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banners">> = Specific
  const handler = {} as typeof import("../../src/app/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/branches">> = Specific
  const handler = {} as typeof import("../../src/app/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../src/app/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/comingSoon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comingSoon">> = Specific
  const handler = {} as typeof import("../../src/app/comingSoon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer-position/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-position">> = Specific
  const handler = {} as typeof import("../../src/app/customer-position/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/branch_customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/branch_customer">> = Specific
  const handler = {} as typeof import("../../src/app/customers/branch_customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/company">> = Specific
  const handler = {} as typeof import("../../src/app/customers/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/credit-change-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/credit-change-request">> = Specific
  const handler = {} as typeof import("../../src/app/customers/credit-change-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/credit-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/credit-policy">> = Specific
  const handler = {} as typeof import("../../src/app/customers/credit-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/group_customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/group_customer">> = Specific
  const handler = {} as typeof import("../../src/app/customers/group_customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/group_parent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/group_parent">> = Specific
  const handler = {} as typeof import("../../src/app/customers/group_parent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/group_party/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/group_party">> = Specific
  const handler = {} as typeof import("../../src/app/customers/group_party/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/limit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/limit">> = Specific
  const handler = {} as typeof import("../../src/app/customers/limit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/national_brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/national_brand">> = Specific
  const handler = {} as typeof import("../../src/app/customers/national_brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/registrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/registrations">> = Specific
  const handler = {} as typeof import("../../src/app/customers/registrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emails">> = Specific
  const handler = {} as typeof import("../../src/app/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../src/app/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../src/app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integration-token/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integration-token">> = Specific
  const handler = {} as typeof import("../../src/app/integration-token/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items">> = Specific
  const handler = {} as typeof import("../../src/app/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members">> = Specific
  const handler = {} as typeof import("../../src/app/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../src/app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roles">> = Specific
  const handler = {} as typeof import("../../src/app/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sales-teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-teams">> = Specific
  const handler = {} as typeof import("../../src/app/sales-teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/types">> = Specific
  const handler = {} as typeof import("../../src/app/types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../src/app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/variants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/variants">> = Specific
  const handler = {} as typeof import("../../src/app/variants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflow-states/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow-states">> = Specific
  const handler = {} as typeof import("../../src/app/workflow-states/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../src/app/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
