var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/customers/group_parent/page.js")
R.c("server/chunks/ssr/_eb9f0105._.js")
R.c("server/chunks/ssr/_0237ce51._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/_88b9a125._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ef35174._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a407645._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_customers_group_parent_page_actions_c748ee2f.js")
R.m(60387)
module.exports=R.m(60387).exports
