var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/customers/branch_customer/page.js")
R.c("server/chunks/ssr/_602faa4c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/_bc3e63b4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ef35174._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a407645._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_customers_branch_customer_page_actions_133f9fb1.js")
R.m(16341)
module.exports=R.m(16341).exports
