var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/_9dcc9392._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_65a7265e.js")
R.c("server/chunks/ssr/[root-of-the-server]__8148c955._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a407645._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_554ec2bf.js")
R.m(68592)
module.exports=R.m(68592).exports
